"""Exam questions per course slug. (prompt, [options], answer_index, explanation, diagram)"""

EXAMS = {
    "python": [
        ("Why do mutable default arguments cause bugs?",
         ["They are re-evaluated at each call", "They are shared across calls of the function",
          "Python copies them deeply", "They cannot be hashed"], 1,
         "The default object is created once at def time and shared across calls.", ""),
        ("What does `yield` do inside a function?",
         ["Returns and terminates", "Raises StopIteration", "Pauses, saving local state for resumption", "Spawns a thread"], 2,
         "Generators pause/resume, keeping local state between yields.", ""),
        ("A decorator that forgets `return wrapper` ...",
         ["works fine", "returns None when the wrapped fn is called", "raises TypeError at import", "caches results"], 1,
         "Without returning the wrapper, the function is replaced by None.", ""),
        ("GIL implication: CPU-bound threads...",
         ["scale linearly", "do not run in parallel in CPython", "crash", "use GPU"], 1,
         "The GIL serializes bytecode execution; use processes for CPU-bound work.", ""),
    ],
    "numpy": [
        ("(3,1) + (1,4) broadcasts to...",
         ["error", "(3,4)", "(4,3)", "(1,1)"], 1,
         "Each size-1 axis stretches to match: result (3,4).", "Images/math/broadcasting.png"),
        ("Which slicing creates a view?",
         ["a[::2]", "a.copy()", "a + 0", "np.array(a)"], 0,
         "Basic slicing returns views; fancy indexing and copies do not.", ""),
        ("Why prefer `a.sum(axis=0)` over Python loops?",
         ["prettier", "vectorized C loops, less overhead, cache-friendly", "more precise", "uses GPU"], 1,
         "ufuncs avoid per-element Python overhead.", ""),
    ],
    "pandas": [
        ("`groupby('city').sales.mean()` returns...",
         ["a DataFrame", "a Series indexed by city", "a numpy scalar", "an error"], 1,
         "Single aggregator on one column -> Series with group keys as index.", ""),
        ("`merge` with how='left' keeps...",
         ["only matches", "all left rows, NaN where no match", "all right rows", "intersection only"], 1,
         "Left join semantics, identical to SQL LEFT JOIN.", ""),
        ("Chained assignment `df[df.a>0]['b']=1` fails because...",
         ["pandas is slow", "it may operate on a temporary copy (SettingWithCopy)", "b is categorical", "NaN"], 1,
         "Use .loc[mask, 'b'] = 1 to write in place.", ""),
    ],
    "mathematics": [
        ("cosine similarity of orthogonal vectors is...",
         ["1", "0", "-1", "undefined"], 1,
         "cos = dot/(|a||b|); dot of orthogonal vectors is 0.", ""),
        ("PCA's first principal component is...",
         ["any eigenvector", "the eigenvector of the covariance matrix with the largest eigenvalue", "the mean vector", "a row of the data"], 1,
         "It is the direction of maximal variance.", ""),
        ("The chain rule in backprop chains...",
         ["sums of gradients", "products of local derivatives along the path", "maxes", "logs"], 1,
         "dL/dx = product of local grads from L back to x.", "Images/math/gradient_descent.jpg"),
    ],
    "machine-learning": [
        ("99% train / 61% val accuracy means...",
         ["great model", "high variance: overfitting", "high bias: underfitting", "data leakage into val"], 1,
         "A large train-val gap is the signature of overfitting.", "Images/ml/overfitting.jpg"),
        ("Precision matters most when...",
         ["false negatives are costly", "false positives are costly", "classes are balanced", "data is small"], 1,
         "Precision = TP/(TP+FP): punishes false alarms.", ""),
        ("K-Means vs DBSCAN: DBSCAN...",
         ["needs k upfront", "finds arbitrary shapes and flags noise, density-based", "is always faster", "is supervised"], 1,
         "DBSCAN needs eps/minPts and handles non-convex clusters.", ""),
        ("Target encoding done on full data before the split...",
         ["improves CV", "leaks the target into training", "regularizes", "balances classes"], 1,
         "Fit the encoding inside the training fold only.", ""),
    ],
    "deep-learning": [
        ("Without zero_grad(), gradients...",
         ["stay zero", "accumulate across iterations", "are clipped", "explode the lr"], 1,
         "PyTorch accumulates grads; stale grads corrupt updates.", "Images/pytorch/training_loop.png"),
        ("Dropout at inference time is...",
         ["kept active", "disabled via model.eval()", "doubled", "replaced by BN"], 1,
         "eval() switches dropout off and freezes BN stats.", ""),
        ("Vanishing gradients in deep nets are worsened by...",
         ["ReLU", "sigmoid activations + depth", "residual connections", "He init"], 1,
         "Small sigmoid derivatives multiply to near zero; ReLU/residuals mitigate.", "Images/dl/backpropagation.jpg"),
        ("BatchNorm during training uses...",
         ["running averages only", "batch statistics", "no statistics", "global dataset stats"], 1,
         "Batch stats at train time; running stats at eval.", ""),
    ],
    "nlp": [
        ("BPE tokens... ",
         ["are always whole words", "are learned subwords balancing vocab size and OOV", "are characters only", "are sentences"], 1,
         "Frequent pairs merge; rare words split into subwords.", "Images/nlp/tokenization.png"),
        ("TF-IDF's IDF down-weights...",
         ["short docs", "terms common across documents", "proper nouns", "stopwords only"], 1,
         "Rare, informative terms get higher IDF.", ""),
    ],
    "transformers": [
        ("Attention(Q,K,V) = ...",
         ["softmax(QK)V", "softmax(QK^T / sqrt(d_k))V", "sigmoid(QK)V", "QK^T V"], 1,
         "Scale before softmax; multiply weights by V.", "Images/transformers/self_attention.jpg"),
        ("Causal masking exists to...",
         ["save memory", "prevent positions from attending to the future", "improve accuracy", "enable batching"], 1,
         "Token t may only attend to positions <= t.", "Images/transformers/attention_mask.png"),
        ("GQA reduces KV-cache memory by...",
         ["quantization", "sharing K/V heads across groups of query heads", "dropping V", "shorter contexts"], 1,
         "Fewer stored K/V heads, quality close to MHA.", "Images/transformers/mqa_gqa.png"),
    ],
    "llm-engineering": [
        ("Temperature controls...",
         ["retrieval randomness", "the softmax flatness over next-token logits", "context length", "cache size"], 1,
         "P = softmax(logits/T); T is generation-only.", "Images/llm/llm_architecture.png"),
        ("KV caching speeds up decoding by...",
         ["parallel attention", "reusing past K/V instead of recomputing them per token", "quantization", "larger batches"], 1,
         "Decode becomes O(1) attention per new token over cached context.", "Images/llm/kv_cache.png"),
        ("LoRA reduces trainable memory by...",
         ["pruning weights", "learning low-rank adapters BA added to frozen W", "8-bit optimizers", "freezing attention"], 1,
         "W' = W + (alpha/r)BA; r << d.", "Images/llm/lora.png"),
        ("RAG reduces hallucination primarily by...",
         ["bigger models", "conditioning generation on retrieved evidence", "lower temperature", "longer prompts"], 1,
         "Grounding in retrieved documents constrains claims.", ""),
    ],
    "rag": [
        ("Increasing chunk size typically...",
         ["raises precision", "hurts precision but adds context completeness", "is always better", "changes nothing"], 1,
         "Bigger chunks dilute the signal; smaller chunks lose context.",
         "Images/rag/rag_lifecycle.png"),
        ("Hybrid retrieval with RRF is robust because...",
         ["RRF is supervised", "lexical and dense signals fail differently", "BM25 is newer", "embeddings are exact"], 1,
         "Vocabulary mismatch hits dense; paraphrase hits lexical - fusion covers both.",
         "Images/rag/hybrid_rrf.png"),
        ("A reranker improves precision because a cross-encoder...",
         ["is faster than ANN", "scores query+document jointly", "uses BM25", "embeds queries"], 1,
         "Joint scoring captures interactions bi-encoders miss.", "Images/rag/rerank_funnel.png"),
        ("Retrieval hits the right doc but the answer is wrong. Debug first...",
         ["the vector DB", "the prompt/context assembly and generation", "the chunk size", "the embedder"], 1,
         "Good retrieval + bad answer points at context construction/prompting.", ""),
    ],
    "langchain-langgraph": [
        ("In LCEL, `prompt | model | parser` builds...",
         ["a subclass", "a Runnable pipeline streaming end-to-end", "a graph DB", "an agent"], 1,
         "The pipe operator composes Runnables.", "Images/langchain/lcel_runnable.png"),
        ("LangGraph nodes...",
         ["share a global namespace", "read and return partial updates to a typed State", "cannot loop", "are classes"], 1,
         "State flows through nodes; reducers merge writes.", "Images/langgraph/graph_state.png"),
        ("interrupt() is used for...",
         ["crashes", "pausing for human approval with persisted state", "caching", "retries"], 1,
         "The checkpointer stores state; resume continues it.", "Images/langgraph/human_in_loop.png"),
    ],
    "ai-agents": [
        ("The ReAct loop interleaves...",
         ["train/infer", "reasoning traces with tool actions and observations", "QA/test", "embed/rank"], 1,
         "Thought -> Action -> Observation until a final answer.", "Images/agents/react_loop.png"),
        ("A reliable agent needs stop conditions because...",
         ["tools are slow", "loops are possible and tokens/costs are finite", "LLMs are deterministic", "state is shared"], 1,
         "Cap steps/tokens; verify before continuing.", "Images/agents/react_loop.png"),
        ("Agent 'semantic memory' typically stores...",
         ["chat logs", "facts/notes retrieved via embeddings", "weights", "tool schemas"], 1,
         "A vector store of durable facts, not raw transcripts.", "Images/agents/memory_types.png"),
    ],
    "mlops": [
        ("Data drift is a change in...",
         ["P(y|x)", "P(x) - the inputs", "the metric", "the registry"], 1,
         "Concept drift is P(y|x); data drift is the input distribution.",
         "Images/mlops/drift_retraining.png"),
        ("MLflow tracking exists so that...",
         ["models train faster", "every run's params/metrics/artifacts are reproducible and comparable", "GPUs are shared", "logs are pretty"], 1,
         "Reproducibility is the whole point.", "Images/mlops/experiment_tracking.png"),
        ("Canary deployment means...",
         ["full cutover", "routing a small traffic share to the new model with automatic rollback", "batch serving", "A/B labels"], 1,
         "Blast-radius control with automated rollback triggers.", ""),
    ],
    "ai-security": [
        ("Indirect prompt injection arrives via...",
         ["the user typing", "content the app retrieves (docs/pages) that the model reads", "GPU drivers", "JWTs"], 1,
         "Malicious instructions hidden in retrieved content.",
         "Images/security/threat_model.png"),
        ("The strongest tenant isolation for RAG is...",
         ["prompt instructions", "enforced data-layer filtering before retrieval", "user agreements", "output filters"], 1,
         "Filter at the data layer; never rely on prompt-only separation.",
         "Images/security/rag_poisoning.png"),
        ("Least privilege for agent tools means...",
         ["more tools", "scoped, read-only-by-default permissions per tool", "admin tokens", "no auth"], 1,
         "Scope tokens per tool; require approval for irreversible actions.", ""),
    ],
}
