"""50 real-world projects, tagged with course + difficulty tier (E..S++)."""

# (course_slug, title, difficulty, objective, [tech])
PROJECTS = [
    ("python", "CLI Expense Tracker", "E", "File-backed CRUD CLI with JSON persistence and input validation.", ["python", "json"]),
    ("python", "Async Web Scraper", "D", "Concurrent scraper with asyncio + rate limiting and CSV export.", ["asyncio", "httpx", "csv"]),
    ("python", "Log Parser Library", "C", "Regex log parser package with pytest suite and typed public API.", ["pytest", "mypy", "packaging"]),
    ("python", "Decorator Profiler Kit", "C", "Timing/retry/memoize decorators with functools and unit tests.", ["functools", "pytest"]),
    ("python", "Multi-threaded Downloader", "B", "Chunked parallel downloads with progress, resume, and checksums.", ["concurrent.futures", "httpx"]),
    ("numpy", "Image Filters from Scratch", "D", "Convolution, thresholding and histogram equalization on ndarray only.", ["numpy", "pillow"]),
    ("numpy", "K-Means in Pure NumPy", "C", "Lloyd's algorithm with k-means++ init and convergence plots.", ["numpy", "matplotlib"]),
    ("numpy", "Benchmark: Loops vs Vectorized", "C", "Measure and explain 10-100x speedups across operations.", ["numpy", "timeit"]),
    ("pandas", "NYC Taxi EDA Report", "D", "Ingest 1M+ rows: cleaning, groupbys, timezone-correct fare analysis.", ["pandas", "matplotlib"]),
    ("pandas", "Sales Dashboard Dataset Builder", "C", "Merge multi-source CSVs into a star-schema analytics table.", ["pandas", "sqlite"]),
    ("pandas", "Data Quality Firewall", "B", "Reusable validation pipeline: schema, ranges, nulls, duplicate reports.", ["pandas", "pandera"]),
    ("mathematics", "PCA from Scratch", "C", "Eigendecomposition vs SVD implementations with reconstruction error.", ["numpy", "sklearn"]),
    ("mathematics", "Gradient Descent Visualizer", "C", "Animated descent on 2D surfaces: SGD/momentum/Adam compared.", ["numpy", "matplotlib"]),
    ("machine-learning", "Titanic End-to-End", "E", "Classic baseline: EDA, pipeline, CV, error analysis.", ["sklearn", "pandas"]),
    ("machine-learning", "Churn Prediction Service", "B", "Feature pipeline + XGBoost + calibration + FastAPI endpoint.", ["xgboost", "fastapi"]),
    ("machine-learning", "Fraud Detection with Class Imbalance", "A", "PR-AUC focus, cost-sensitive thresholds, SMOTE vs class weights.", ["imbalanced-learn", "lightgbm"]),
    ("machine-learning", "Credit Risk Scorecard", "A", "WOE binning, IV selection, monotonic constraints, regulatory docs.", ["sklearn", "optbinning"]),
    ("machine-learning", "ML Model Zoo CLI", "B", "Train/eval 8 classifiers with one command and comparison report.", ["sklearn", "typer"]),
    ("deep-learning", "MLP on MNIST", "E", "Pure PyTorch: training loop, val split, checkpointing.", ["pytorch"]),
    ("deep-learning", "CNN CIFAR-10 with Augmentation", "C", "ResNet-style blocks, augmentation, LR schedule, 90%+ accuracy.", ["pytorch", "torchvision"]),
    ("deep-learning", "Training Loop Framework", "A", "Reusable Trainer: callbacks, mixed precision, early stopping, logging.", ["pytorch"]),
    ("deep-learning", "Grad-CAM Explainer", "B", "Visualize CNN attention on predictions; sanity-check the maps.", ["pytorch", "torchcam"]),
    ("nlp", "Spam Classifier (TF-IDF)", "D", "Classic pipeline with calibration and threshold analysis.", ["sklearn", "nltk"]),
    ("nlp", "NER with Transformers", "B", "Fine-tune a token-classification model, entity-level F1.", ["transformers", "seqeval"]),
    ("nlp", "Semantic Search Mini", "C", "Sentence-transformers index over 10k sentences with eval.", ["sentence-transformers", "faiss"]),
    ("transformers", "Attention Visualizer", "C", "Interactive head/viewer for real model attention maps.", ["transformers", "plotly"]),
    ("transformers", "KV Cache Benchmark", "A", "Measure prefill/decode latency vs context; GQA vs MHA memory.", ["pytorch", "transformers"]),
    ("transformers", "Mini-GPT from Scratch", "S", "Train a char-level GPT; document every shape and choice.", ["pytorch"]),
    ("llm-engineering", "Prompt Playground", "B", "Compare models/params side-by-side with cost + latency tracking.", ["fastapi", "react"]),
    ("llm-engineering", "Structured Output Extractor", "B", "Resume -> validated JSON with retry-on-validation-error loops.", ["pydantic", "openai"]),
    ("llm-engineering", "Semantic Cache Layer", "A", "Embedding cache with similarity threshold; measure hit-rate vs quality.", ["redis", "sentence-transformers"]),
    ("llm-engineering", "LoRA Fine-Tune Lab", "S", "QLoRA a small LLM on custom data; eval vs base with held-out sets.", ["peft", "bitsandbytes"]),
    ("rag", "Doc-QA over Your Notes", "D", "Chunk, embed, retrieve, cite - the complete basic loop.", ["sentence-transformers", "faiss"]),
    ("rag", "Hybrid Search Engine", "A", "BM25 + dense + RRF; ablate each component honestly.", ["rank-bm25", "qdrant"]),
    ("rag", "RAG Evaluation Harness", "A", "hit@k, MRR, faithfulness; failure injection + per-query traces.", ["ragas", "langsmith"]),
    ("rag", "Multimodal PDF RAG", "S", "Tables + images + text ingestion; ColBERT-style reranking.", ["unstructured", "clip"]),
    ("rag", "Enterprise RAG Platform", "S++", "Multi-tenant, ACL-filtered, cached, observed, evaluated RAG.", ["fastapi", "pgvector", "redis"]),
    ("langchain-langgraph", "LCEL Chains Cookbook", "C", "10 chains: routing, fallbacks, streaming, structured output.", ["langchain"]),
    ("langchain-langgraph", "Stateful Support Agent", "B", "LangGraph agent with memory, tools, and escalation interrupts.", ["langgraph"]),
    ("langchain-langgraph", "Multi-Agent Research Crew", "A", "Supervisor + researcher + writer + reviewer with shared state.", ["langgraph", "langchain"]),
    ("ai-agents", "ReAct Agent from Scratch", "C", "Tool-calling loop without frameworks; hard stop conditions.", ["openai", "pydantic"]),
    ("ai-agents", "SQL Agent with Guardrails", "B", "NL -> SQL with schema grounding, injection blocks, query limits.", ["sqlalchemy"]),
    ("ai-agents", "Browser Automation Agent", "A", "Playwright agent with DOM grounding and human approval gates.", ["playwright"]),
    ("ai-agents", "Coding Agent Sandbox", "S", "Plan -> patch -> test loop with sandboxed execution and retries.", ["subprocess", "docker"]),
    ("mlops", "MLflow Experiment Tracker", "D", "Track params/metrics/artifacts for a full training sweep.", ["mlflow", "sklearn"]),
    ("mlops", "Drift Detection Service", "B", "PSI/KS monitors on a live feed with alerting thresholds.", ["evidently", "fastapi"]),
    ("mlops", "CI/CD for ML", "A", "GitHub Actions: test -> train -> eval gate -> registry -> deploy.", ["github-actions", "docker"]),
    ("mlops", "Feature Store Mini", "S", "Offline/online views, point-in-time correctness, freshness SLAs.", ["feast", "redis"]),
    ("ai-security", "Prompt Injection Test Suite", "B", "Red-team harness: direct/indirect payloads with pass/fail reports.", ["httpx", "pytest"]),
    ("ai-security", "Tenant-Isolated RAG", "S", "Prove isolation with adversarial tests across user boundaries.", ["pgvector", "pytest"]),
]
